### ISSUE TITLE
Bool CAS and Toggle don't work together

### ISSUE THREAD

**Issue by jfancher** [uber-go/atomic#61]
```go
var b atomic.Bool
b.Store(true)         // true
b.Toggle()            // false
b.CAS(false, true)    // true ?
fmt.Println(b.Load()) // "false"
```
`CAS` assumes a direct equality check with `1` or `0` but the rest of the functions only look at the lowest bit, which `Toggle` takes advantage of.

**Comment by prashantv** [comment]
Great catch! You're completely right -- `CAS` requires knowledge of the entire value to swap, while everything else can rely on just the last bit.

I think we have a couple of options here:
1. Don't rely on the last bit, but check the entire value. This require `Toggle` to become a loop that uses `CAS`, something like:

```
for {
  old := b.Load()
  if b.CAS(old, !old) {
    return true
  }
}
```

2. Modify `CAS` to do a load of the int value, and use that for an `atomic.CompareAndSwap`. This requires a loop in `CAS` though, since the API for the user should be that the swap succeeds if the old value matches, but it's possible that the old value is `3`, but then a user does `b.Store(true)` which modifies the value, even though it's still `true`, the `CAS` would fail.

I'll send a PR for (1) since it's simpler, and I'd prefer the semantics of `CAS` to be a single `CompareAndSwap`.

cc @abhinav
